### PR TITLE
register page UI inhanced

### PR DESCRIPTION
**Pull request by aman-roy**
#8 resolved.
Screenshot from 2019-10-15 15-37-07

### CODE REVIEW

**Comment by tulikavijay** [comment]
Great! thankyou for working on this so fast. I would like to add some minor changes : 
1. Register need not be underlined
2. I am not sure about the gray color box.
3. you can use the blue color that appears on the carousel for the submit button.

**Comment by aman-roy** [comment]
fixed the above issue. Please check.

Screenshot from 2019-10-15 18-16-18

**Comment by perun-01** [comment]
i could create more attractive UI then this. if is it still open??, let me knw.

**Comment by tulikavijay** [comment]
@perun-01 it's still open. You can experiment with the UI :)

**Comment by mridul-arora** [comment]
Is this still open or I can maybe work on this. Let me know.

**Pull request merged**
