### PR TITLE
fixed wrong command

### PR DESCRIPTION
**Pull request by perun-01**
I have corrected the wrong command in the readme.md file ([#13](https://github.com/tulikavijay/CBT-therapy/issues/13) issue)
**old** command: git checkout branch local-dev
**New** command: git checkout local-dev

### CODE REVIEW

**Comment by perun-01** [comment]
Hey tulikavijay, in this PR ,  a large number of files are changed because the PR is created for local-dev branch(as mentioned in contributing section) but the error was in maaster branch and the local-dev branch is lagging from master branch..because of which large number of files have been changed. Even the README.md file content is different in local-dev branch .
If u want me Send another PR for the same, then i ll do but by creating a different branch , so that no conflict would occur.

**Comment by tulikavijay** [comment]
For README.md you can directly work on the master branch or create a new branch and add only that single file to the staging area.
Apart from that, the branch issues - I am aware of the lag on the local-dev. I am thinking of removing it from the README.md. But before that i would like to confirm - if localhost is working fine on master. Does it work for you?

**Comment by perun-01** [comment]
Okay i will create another PR. Actually i am a lit bit confused that either my PR has been merged or reverted . And yes it worked for me in localhost while i was thinking of giving it a logo(which i m working on). But i suggest u to take a backup of both , so that there is no loss of data in any case.

**Comment by tulikavijay** [comment]
No, I meant removing local dev command from the readme file, not removing it completely from the project. And your pr has been reverted because i thought only the readme had been updated.

**Comment by perun-01** [comment]
Okay then i have reforked the repo and delete the previous PR, and will create a new branch and will send u a new PR again .

**Comment by perun-01** [comment]
Hey tulikavijay,  I have created another PR(#18 ) for the same. Go check it out.

**Pull request merged**
